require 'build_game'
require 'net/http'

class GameSubmitter
  TOKEN_REGEX = "//meta[@name='csrf-token']"

  def submit_games(new_uri, count, start_date, user, pwd)
    new_uri = "http://#{new_uri}" unless new_uri.index("http")
    raise ArgumentError, "URI is missing port!" unless new_uri.index(":", 5)
    uri = URI new_uri
    # Ensure game starts on a Monday
    date = adjust_date_to_monday start_date
    
    gb = BuildGame.new count

    # Create an imperilment game for each game generated by game builder
    gb.games.each do |rounds|
      Net::HTTP.start uri.host, uri.port do |http|
        result = log_in_response http, uri, user, pwd
        result = create_game_response(
          http,
          uri,
          result['set-cookie'],
          (date + (60*60*24*7)),
        )
        game_id = get_id result, uri

        # Create the categories required for the current game
        rounds.each do |category|
          result = create_category_response(
            http,
            uri,
            result['set-cookie'],
            category.name,
          )
          category_id = get_id result, uri

          # Create the answers for the current category
          category.clues.each do |clue|
            result = create_answer(http, uri, result['set-cookie'],
                                   game_id, category_id, date,
                                   clue.answer, clue.question, clue.value,)
            date += (60*60*24) 
          end
        end
      end
    end
  end

  private
  def get_token body
    Nokogiri.parse(body).xpath(TOKEN_REGEX)[0]['content']
  end

  def get_id result, uri
    first = uri.to_s.length + 1
    result.to_hash["location"][0][(uri.to_s.length + 1)..-1].to_i
  end

  def adjust_date_to_monday date
    tmp = date.dup
    until tmp.monday? do
      tmp += (60*60*24)
    end
    tmp
  end

  def log_in_response http, uri, user, pwd
    # Get form page (for token and cookie)
    uri.path = '/users/sign_in'
    req = Net::HTTP::Get.new uri
    res = http.request req

    # Sign in
    req = Net::HTTP::Post.new uri
    req.set_form_data(
      'authenticity_token': get_token(res.body),
      'user[email]': user,
      'user[password]': pwd,
      'user[remember_me]': 1,
      'commit': 'Sign in',
    )
    req['Cookie'] = res['set-cookie']

    http.request req
  end

  def create_game_response http, uri, cookie, date
    # Get form page (for token and cookie)
    uri.path = '/games/new'
    req = Net::HTTP::Get.new uri
    req['Cookie'] = cookie
    res = http.request req

    # Create Game
    uri.path = '/games'
    req = Net::HTTP::Post.new uri
    req.set_form_data(
      'authenticity_token': get_token(res.body),
      'game[ended_at]': date,
      'commit': 'Create Game',
    )

    req['Cookie'] = res['set-cookie']

    http.request req
  end

  def create_category_response http, uri, cookie, name
    # Get form page (for token and cookie)
    uri.path = '/categories/new'
    req = Net::HTTP::Get.new uri
    req['Cookie'] = cookie
    res = http.request req

    uri.path = "/categories"
    req = Net::HTTP::Post.new uri
    req.set_form_data(
      'authenticity_token': get_token(res.body),
      'category[name]': name,
      'commit': 'Create Category',
    )
    req['Cookie'] = res['set-cookie']
    http.request req
  end

  def create_answer http, uri, cookie, game_id, cat_id, date, ans, ques, val
    # Get form page (for token and cookie)
    uri.path = "/games/#{game_id}/answers/new"
    req = Net::HTTP::Get.new uri
    req['Cookie'] = cookie
    res = http.request req

    uri.path = "/games/#{game_id}/answers"
    req = Net::HTTP::Post.new uri
    req.set_form_data(
      'authenticity_token': get_token(res.body),
      'answer[category_id]': cat_id,
      'answer[answer]': ans,
      'answer[correct_question]': ques,
      'answer[amount]': val,
      'answer[start_date]': date
    )
    req['Cookie'] = res['set-cookie']

    http.request req
  end
end
